language: objective-c
xcode_workspace: TravisCI.xcworkspace # path to your xcodeproj folder
xcode_scheme: TravisCI
osx_image: xcode12

script:
  - xcodebuild clean build -sdk iphonesimulator -workspace TravisCI.xcworkspace -scheme TravisCI CODE_SIGNING_REQUIRED=NO
